# Global Values
repoUrl: 'https://github.com/Pacobart/argo-eks-addons'
targetRevision: HEAD
region: ''
account: ''
clusterName: ''
environment: ''
destinationServer: ''
argoNamespace: ''
argoProject: ''
domain_name_suffix: ''

# AWS Load Balancer Controller Values
awsLoadBalancerController:
  enable: true
  createNamespace: true
  serviceAccountName:
  podDisruptionBudget:
    maxUnavailable: 1
  respectIgnoreDifferences: true
  ignoreDifferences:
  - group: ""
    kind: "Secret"
    jsonPointers:
    - /data
  - group: "admissionregistration.k8s.io"
    kind: "MutatingWebhookConfiguration"
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
  - group: "admissionregistration.k8s.io"
    kind: "ValidatingWebhookConfiguration"
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'

# Cert Manager Values
certManager:
  enable: true
  createNamespace: true
  serviceAccountName:

# Cert Manager CSI Driver Values
certManagerCsiDriver:
  enable: true

# External DNS Values
externalDns:
  enable: true
  createNamespace: true
  serviceAccountName:
  zoneIdFilters:

# Gatekeeper Values
gatekeeper:
  enable: true
  createNamespace: true

# Nginx Values
ingressNginx:
  enable: true
  createNamespace: true

# Karpenter Values
karpenter:
  enable: true
  createNamespace: true
  serviceAccountName:
  interruptionQueue:

# Argo Rollout Values
argoRollouts:
  enable: true
  createNamespace: true

# Argo Rollout Values
argoWorkflows:
  enable: false

# Metrics Server Values
metricsServer:
  enable: true

# kubecost Values
kubecost:
  enable: true

# Kube Prometheus Stack
kubePrometheusStack:
  enable: true

# AWS Otel Collector Values
awsOtelCollector:
  enable: true
  createNamespace: true
  otlpEndpoint:
  resourceAttributes:

opentelemetryCollector:
  enable: true
  serviceAccountName:

# AWS for Fluent Bit Values
awsForFluentBit:
  enable: true
  createNamespace: true
  logGroupName:
  serviceAccountName: