external-dns:
  serviceAccount:
    create: true
    name: "external-dns"
  provider: "aws"
  policy: sync
  serviceMonitor:
    enabled: false
  zoneIdFilters:
  txtOwnerId:
  image:
    repository: registry.k8s.io/external-dns/external-dns
    tag: v0.14.1